#pragma config(Sensor, dgtl2,  rightls,        sensorTouch)
#pragma config(Sensor, dgtl3,  leftls,         sensorTouch)
#pragma config(Motor,  port2,           motorl,        tmotorServoContinuousRotation, openLoop, reversed)// left wheel
#pragma config(Motor,  port3,           slider,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           claw,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           clawfront,     tmotorServoStandard, openLoop, reversed)
#pragma config(Motor,  port8,           arm,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           motorr,        tmotorServoContinuousRotation, openLoop)// right wheel
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//[1,2]
float ranalogx, lanalogx;
float ranalogy, lanalogy;
bool on = true;
float thresh = 15;
float thresh2 = thresh + 5;
int lowerbound = -70;//front claw
int upperbound = 75;//front claw
int lowerbound2 = -60;//back claw
int upperbound2 = 0;//back claw
int speed = 1; // Raise to slow


task drive(){
	while(on){
		if(vexRT(Btn5U)){
			ranalogx = 0;
		}
		if(vexRT(Btn5D)) {
			motor[motorr] = ranalogy;
			motor[motorl] = lanalogy;
			} else if(vexRT(Btn7D)) {
			if(abs(ranalogx)/abs(ranalogy)>15){
				ranalogy = 0;
			}
			motor[motorr] = (-ranalogy)+(ranalogx);// right wheel
			motor[motorl] = (-ranalogy)+(-ranalogx);// left wheel
			} else {
			if(abs(ranalogx)/abs(ranalogy)>15){
				ranalogy = 0;
			}
			motor[motorr] = (ranalogy)+(-ranalogx);
			motor[motorl] = (ranalogy)+(ranalogx);
		}
	}
}
task manipulator() {
	while(on) {

		if(vexRT[Btn6U]) {// move the claws up and down
			motor[arm] = lanalogy;
			} else {
			motor[arm] = 0;
		}
		// Tanner here! Was just gonna stay home and see if I could fix it. Text me if you need :P
		//Dalton here, I'm working on fixing things already.  The limit switches work now.
		if(vexRT[Btn6D]){
			if((SensorValue(rightls) == 0)&&(lanalogx>0)){//This line of code is for the sliders on the robot.
				//We need it for not breaking the manipulators by coming off the robot.
				motor[slider] = lanalogx;
				} else if((SensorValue(leftls) == 0)&&(lanalogx<0)){
				motor[slider] = lanalogx;
				} else if((SensorValue(leftls) != 0)&&(SensorValue(rightls) != 0)){
				motor[slider] = lanalogx;
				} else {
				motor[slider] = 0;
			}
		}
		if(vexRT(Btn8R)&&motor[claw]>lowerbound){// front claw (open the claw)
			motor[claw] = motor[claw] - 1;
			wait1Msec(speed);
			} else if(vexRT(Btn8L)&&motor[claw]<upperbound) {// front claw (close the claw)
			motor[claw] = motor[claw] + 1;
			wait1Msec(speed);
		}

		if(vexRT(Btn7R)&&motor[clawfront]>lowerbound2){// back claw (open the claw)
			motor[clawfront] = motor[clawfront] - 1;
			wait1Msec(speed);
			} else if(vexRT(Btn7L)&&motor[clawfront]<upperbound2) {// back claw (close the claw)
			motor[clawfront] = motor[clawfront] + 1;
			wait1Msec(speed);
		}
	}
}

task main(){
	startTask(drive);
	startTask(manipulator);
	while(on){
		ranalogx = vexRT(Ch1);
		if(abs(ranalogx)<thresh2){
			ranalogx = 0;
		}
		ranalogy = vexRT(Ch2);
		if(abs(ranalogy)<thresh){
			ranalogy = 0;
		}
		lanalogy = vexRT(Ch3);
		if((abs(lanalogy)<thresh)&&!vexRT(Btn5D)){
			lanalogy = 0;
		}
		lanalogx = vexRT(Ch4);
		if(abs(lanalogx)<thresh){
			lanalogx = 0;
		}
	}
}
