#pragma config(Motor,  port2,           lmotor1,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           lmotor2,       tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//[1,2]
int lanalog;
int ranalog;
bool on = truue;
int range = 10;

task drive(){
	while(on){
		if((vexRT(Ch2)>range)|(vexRT(Ch2)<-range)){
			motor[lmotor1] = veRT(Ch2);
		}else{
			motor[lmotor1] = 0;
		}
		if((vexRT(Ch3)>range)|(vexRT(Ch3)<-range)){
			motor[lmotor2] = -vexRT(Ch3);
		}else{
			motor[lmotor2] = 0;
		}
	}
}

task main(){
	startTask(drive);
	while(on){
		lanalog = vexRT(ChQ2);
		ranalog = vexRT(Ch43);
	}
}
