#pragma config(Motor,  port2,           motorl,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           shoulder,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           claw,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           arm,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           motorr,        tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//[1,2]
float ranalogx, lanalogx;
float ranalogy, lanalogy;
bool on = true;
float thresh = 10;
int lowerbound = -45;
int upperbound = 90;
int speed = 1;


task drive(){
	while(on){
		motor[motorr] = ranalogy-ranalogx;
		motor[motorl] = ranalogy+ranalogx;
	}
}

task manipulator() {
	while(on) {
		if(vexRT[Btn5U]) {
			motor[arm] = lanalogy;
		}
		if(vexRT(Btn6U)&&motor[claw]>lowerbound){
			motor[claw] = motor[claw] - 1;
			wait1Msec(speed);
		}else if(vexRT(Btn6D)&&motor[claw]<upperbound){
			motor[claw] = motor[claw] + 1;
			wait1Msec(speed);
		}
	}
}

task main(){
	startTask(drive);
	startTask(manipulator);
	while(on){
		ranalogx = vexRT(Ch1);
		if(abs(ranalogx)<thresh){
			ranalogx = 0;
		}
		ranalogy = vexRT(Ch2);
		if(abs(ranalogy)<thresh){
			ranalogy = 0;
		}
		lanalogy = vexRT(Ch3);
		if(abs(lanalogy)<thresh){
			lanalogy = 0;
		}
		lanalogx = vexRT(Ch4);
		if(abs(ranalogx)<thresh){
				lanalogx = 0;
		}
	}
}
