#pragma config(Motor,  port2,           lmotorl,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           shoulder,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           claw,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           arm,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           lmotorr,       tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//[1,2]
float ranalogx, lanalogx;
float ranalogy, lanalogy;
bool on = true;
float thresh = 10;

task drive(){
	while(on){
		motor[lmotorr] = ranalogy+ranalogx;
		motor[lmotorl] = ranalogy-ranalogx;
	}
}

task manipulator() {
	while(on) {
		if(vexRT[Btn5U]){
			motor[arm] = lanalogy;
		} else {
			motor[arm] = 0;
		}
		if(vexRT[Btn6D]){
			motor[claw] = 0;
		}
		if(vexRT[Btn6U]){
			motor[claw] = 45;
		}
	}
}

task main(){
	startTask(drive);
	startTask(manipulator);
	while(on){
		ranalogx = vexRT(Ch1);
		if(abs(ranalogx)<thresh){
			ranalogx = 0;
		}
		ranalogy = vexRT(Ch2);
		if(abs(ranalogy)<thresh){
			ranalogy = 0;
		}
		lanalogx = vexRT(Ch4);
			if(abs(lanalogx)<thresh){
				lanalogx = 0;
		}
		lanalogy = vexRT(Ch3);
			if(abs(lanalogy)<thresh){
				lanalogy = 0;
		}
	}
}
